hello-worl
title: my awesome blog
author: Tuan Anh
email: s3878655@rmit.edu.vn
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyllrb

# Build settings
markdown: kramdown
theme: mimina
 jekyll-feed
 jekyll-seo-tag
