title: Your awesome title
email: your-email@example.com
description: hihi
url: https://nickrmit3878655.github.io/nickrmit3878655newblog.github.io/"" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
